const keywordsByCategory = {
  Příroda: [
    "příroda",
    "zvíře",
    "zvířata",
    "divoké zvíře",
    "savci",
    "plazi",
    "obojživelníci",
    "les",
    "houby",
    "mech",
    "keře",
    "háj",
    "prales",
    "strom",
    "listí",
    "větve",
    "kořeny",
    "jehličnan",
    "listnáč",
    "klima",
    "počasí",
    "teplota",
    "déšť",
    "sucho",
    "sníh",
    "ledovec",
    "oteplování",
    "ekologie",
    "ekosystém",
    "životní prostředí",
    "uhlíková stopa",
    "recyklace",
    "vítr",
    "poryv",
    "bouře",
    "vichřice",
    "pták",
    "ptačí",
    "hnízdo",
    "peří",
    "dravci",
    "zpěv ptáků",
    "chráněný",
    "ohrožený druh",
    "rezervace",
    "národní park",
    "ochrana přírody",
    "zahrada",
    "rostliny",
    "květiny",
    "zahradničení",
    "hmyz",
    "motýl",
    "včela",
  ],
  Věda: [
    "věda",
    "vědecký",
    "vědec",
    "vědkyně",
    "bádání",
    "poznání",
    "objev",
    "objevit",
    "výzkum",
    "výzkumník",
    "zkoumání",
    "analýza",
    "studie",
    "testování",
    "experiment",
    "pokusy",
    "hypotéza",
    "výsledek",
    "měření",
    "metoda",

    "vesmír",
    "planeta",
    "hvězda",
    "galaxie",
    "kosmos",
    "astronomie",
    "raketa",
    "sonda",
    "teleskop",
    "černá díra",

    "laboratoř",
    "zkumavka",
    "pipeta",
    "ochranné brýle",
    "bílý plášť",
    "výbava do laboratoře",

    "nobelova",
    "nobelova cena",
    "ocenění",
    "laureát",
    "objevitel",

    "fyzika",
    "síla",
    "energie",
    "hmotnost",
    "rychlost",
    "zrychlení",
    "gravitace",
    "elektřina",
    "magnet",
    "zvuk",
    "světlo",

    "chemie",
    "chemik",
    "molekula",
    "prvky",
    "sloučenina",
    "reakce",
    "tabulka prvků",
    "látka",
    "kyselina",
    "zásada",
    "pH",

    "biologie",
    "organismus",
    "buňka",
    "tkáň",
    "rostlina",
    "živočich",
    "lidské tělo",
    "DNA",
    "gen",
    "evoluce",

    "mikroskop",
    "mikroorganismus",
    "bakterie",
    "vir",
    "pozorování",
    "zvětšení",
    "sklíčko",
  ],
  Technologie: [
    "technologie",
    "technologický",
    "vynález",
    "novinka",
    "vývoj",
    "zařízení",
    "moderní",
    "inovace",
    "digitální",
    "elektronika",

    "robot",
    "robotický",
    "automat",
    "stroj",
    "inteligentní stroj",
    "ovládání",
    "programovatelný",

    "AI",
    "umělá inteligence",
    "umělý mozek",
    "strojové učení",
    "neurony",
    "algoritmus",
    "chatbot",

    "počítač",
    "notebook",
    "klávesnice",
    "monitor",
    "harddisk",
    "procesor",
    "hardware",
    "software",

    "mobil",
    "telefon",
    "chytrý telefon",
    "smartphone",
    "tablet",
    "displej",
    "nabíječka",

    "aplikace",
    "apka",
    "program",
    "instalace",
    "stahování",
    "update",
    "mobilní hra",
    "nástroj",

    "internet",
    "web",
    "online",
    "síť",
    "prohlížeč",
    "webová stránka",
    "wifi",
    "signál",

    "programování",
    "kódování",
    "kód",
    "jazyk",
    "HTML",
    "JavaScript",
    "Python",
    "blokové programování",

    "chytrý",
    "smart",
    "inteligentní",
    "automatický",
    "připojený",
    "bezdrátový",
    "ovladatelný",

    "software",
    "operační systém",
    "aplikace",
    "program",
    "systém",
    "platforma",
  ],
  Sport: [
    "sport",
    "sportovní",
    "atletika",
    "soutěž",
    "turnaj",
    "mistrovství",
    "zápas",
    "trénink",
    "disciplína",
    "reprezentace",

    "fotbal",
    "fotbalista",
    "branka",
    "gól",
    "hřiště",
    "míč",
    "rozhodčí",
    "liga",
    "kopaná",
    "hráč",

    "hokej",
    "hokejista",
    "puk",
    "brankář",
    "kluziště",
    "hokejka",
    "gólman",
    "hokejová liga",

    "basketbal",
    "basketbalista",
    "koš",
    "driblování",
    "míč",
    "tým",
    "hráč",
    "palubovka",

    "cyklistika",
    "cyklista",
    "závod",
    "kolo",
    "silnice",
    "etapa",
    "Tour",
    "helma",

    "plavání",
    "bazén",
    "plavec",
    "dráha",
    "styl",
    "závody",
    "kraul",
    "motýlek",
    "startovní blok",

    "olympiáda",
    "olympijské hry",
    "medaile",
    "zlato",
    "stříbro",
    "bronz",
    "sportovec",
    "reprezentant",
    "ceremonie",

    "běh",
    "skok",
    "hod",
    "maraton",
    "štafeta",
    "stadion",
    "fitness",
    "pohyb",
    "kondice",

    "trénink",
    "trenér",
    "cvičení",
    "zlepšení",
    "technika",
    "strategie",
    "rozcvička",
    "posilování",
  ],
  Zábava: [
    "zábava",
    "odpočinek",
    "legrace",
    "smích",
    "volný čas",
    "relaxace",

    "film",
    "filmový",
    "filmování",
    "režisér",
    "herec",
    "herečka",
    "promítání",
    "trailer",

    "pohádka",
    "pohádkový",
    "pohádkář",
    "večerníček",
    "kouzlo",
    "princezna",
    "drak",
    "dobrodružství",

    "hra",
    "videohra",
    "stolní hra",
    "karetní hra",
    "zábavná hra",
    "hraní",
    "hrát",
    "herní",
    "gamepad",

    "seriál",
    "epizoda",
    "postava",
    "děj",
    "oblíbený seriál",
    "animovaný seriál",
    "streamování",
    "Netflix",
    "YouTube Kids",

    "disney",
    "pixar",
    "dreamworks",
    "disneyovka",
    "mickey",
    "minnie",
    "frozen",
    "encanto",
    "zootopia",

    "kino",
    "promítání",
    "plátno",
    "sedadlo",
    "popcorn",
    "kinozážitek",
    "premiéra",
    "multikino",

    "písnička",
    "hudba",
    "zpěv",
    "melodie",
    "dětská písnička",
    "refrén",
    "zpívání",
    "karaoke",
    "hlas",

    "karikatura",
    "vtip",
    "komiksová postava",
    "obrázek",
    "ilustrace",
    "vtipný obrázek",

    "komiks",
    "bublina",
    "hrdina",
    "superhrdina",
    "čtení",
    "komiksový sešit",
    "grafický román",

    "animace",
    "animovaný",
    "animátor",
    "pohyb",
    "kreslení",
    "3D animace",
    "2D animace",
    "scéna",
    "film pro děti",
  ],
  Historie: [
    "historie",
    "dějiny",
    "dějepis",
    "minulost",
    "události",
    "vývoj",
    "starověk",
    "pravěk",
    "moderní dějiny",

    "král",
    "královna",
    "princ",
    "princezna",
    "panovník",
    "vládce",
    "dynastie",
    "království",
    "monarchie",

    "hrad",
    "zámek",
    "pevnost",
    "bašta",
    "věž",
    "opevnění",
    "středověká stavba",
    "rytířský hrad",

    "bitva",
    "boj",
    "válka",
    "šarvátka",
    "vojsko",
    "rytíř",
    "zbroj",
    "meč",
    "štít",
    "válečník",

    "středověk",
    "temný věk",
    "rytířství",
    "feudalismus",
    "panství",
    "cech",
    "poddanský",
    "klášter",

    "objev",
    "objevitel",
    "expedice",
    "dobývání",
    "nový svět",
    "kolonizace",
    "dobrodruh",
    "průzkum",

    "vládce",
    "císař",
    "vůdce",
    "guvernér",
    "vláda",
    "trůn",
    "panovník",
    "moc",

    "archeologie",
    "vykopávka",
    "archeolog",
    "kostra",
    "nález",
    "artefakt",
    "zkamenělina",
    "vykopávky",
    "pravěk",

    "muzeum",
    "výstava",
    "exponát",
    "kurátor",
    "sbírka",
    "historický předmět",
    "návštěva",
    "učebna",

    "časová osa",
    "letopočet",
    "staré civilizace",
    "pyramidy",
    "Řím",
    "Řecko",
    "vikingové",
    "Kelti",
    "Slované",
  ],
  Zdraví: [
    "doktor",
    "lékař",
    "sestřička",
    "ambulance",
    "ordinace",
    "nemocnice",
    "zdravotník",
    "pediatr",
    "ošetření",

    "nemoc",
    "nachlazení",
    "chřipka",
    "rýma",
    "horečka",
    "kašel",
    "bolest",
    "zranění",
    "úraz",
    "lék",
    "antibiotika",

    "zdraví",
    "péče",
    "tělesná pohoda",
    "duševní zdraví",
    "wellbeing",
    "zdravý životní styl",
    "vyvážená strava",

    "vitamín",
    "vitamíny",
    "minerály",
    "doplňky",
    "zdravá výživa",
    "ovoce",
    "zelenina",
    "imunita",

    "cvičení",
    "pohyb",
    "tělocvik",
    "rozcvička",
    "fitko",
    "protažení",
    "běh",
    "chůze",
    "gymnastika",

    "tělo",
    "orgán",
    "sval",
    "kostra",
    "pokožka",
    "kosti",
    "ruce",
    "nohy",
    "srdce",
    "mozek",
    "plíce",

    "zuby",
    "zubní hygiena",
    "kartáček",
    "zubní pasta",
    "zubař",
    "čištění zubů",
    "plomba",

    "prevence",
    "očkování",
    "návštěva lékaře",
    "kontrola",
    "zdravotní prohlídka",
    "hygiena",
    "mytí rukou",

    "sport",
    "tělocvik",
    "běhání",
    "míčové hry",
    "cyklistika",
    "plavání",
    "skákání",
    "soutěžení",
    "závod",

    "odpočinek",
    "spánek",
    "relaxace",
    "energie",
    "pitný režim",
    "pití vody",
  ],
  Cestování: [
    "zájezd",
    "výlet",
    "exkurze",
    "dovolená",
    "pobyt",
    "poznávací zájezd",
    "prohlídka",

    "cestování",
    "cesta",
    "dobrodružství",
    "putování",
    "expedice",
    "výprava",
    "turistika",
    "toulky",

    "země",
    "stát",
    "kontinent",
    "planeta",
    "národ",
    "kultura",
    "obyvatelé",

    "svět",
    "koutek světa",
    "zahraničí",
    "daleké kraje",
    "světadíl",
    "globus",

    "letadlo",
    "vlak",
    "autobus",
    "doprava",
    "let",
    "letiště",
    "letenka",
    "lodní doprava",

    "mapa",
    "kompas",
    "navigace",
    "směr",
    "orientace",
    "trasa",
    "průvodce",
    "atlas",

    "prázdniny",
    "volno",
    "léto",
    "letní tábor",
    "odpočinek",
    "zábava",
    "kempování",
    "nocleh",
    "stanování",

    "dobrodružství",
    "napětí",
    "příběh",
    "zážitek",
    "hledání pokladu",
    "objev",
    "cesta za poznáním",

    "krajina",
    "příroda",
    "hory",
    "lesy",
    "moře",
    "řeka",
    "město",
    "vesnice",
    "výhled",
    "významné místo",

    "památka",
    "historie",
    "hrad",
    "zámek",
    "kostel",
    "most",
    "socha",
    "muzeum",
    "pamětihodnost",
  ],
};

export default keywordsByCategory;
